// packages/bindings/vue3/src/lib/Paintable.vue
<template>
  <div
    id="vue-paintable-container"
    :style="{
      width: `${width}px`,
      height: `${height}px`
    }"
  >
    <canvas ref="canvas" :width="width" :height="height"></canvas>

    <div id="vue-paintable-inner" :style="{ height: '100%', width: '100%' }">
      <slot></slot>
    </div>
  </div>
</template>

<script lang="ts">
import { Paintable as PaintableCore } from "paintablejs";
import { defineComponent, onMounted, ref, watch } from "vue";

export default defineComponent({
  props: {
    // required
    width: {
      type: Number,
      required: true
    },
    height: {
      type: Number,
      required: true
    },
    active: {
      type: Boolean,
      required: true
    },
    //optional
    scaleFactor: {
      type: Number,
      required: false
    },
    useEraser: {
      type: Boolean,
      required: false
    },
    thicknessEraser: {
      type: Number,
      required: false
    },
    thickness: {
      type: Number,
      required: false
    },
    color: {
      type: String,
      required: false
    },
    image: {
      type: String,
      required: false
    }
  },
  emits: ["longPress", "save"],
  setup(props, { emit }) {
    const paintable = ref<null | PaintableCore>(null);
    const canvas = ref<HTMLCanvasElement | null>(null);

    watch(
      () => props.active,
      active => {
        paintable.value?.setActive(active!);
      }
    );

    watch(
      () => props.useEraser,
      useEraser => {
        paintable.value?.setUseEraser(useEraser!);
      }
    );

    watch(
      () => props.thicknessEraser,
      thicknessEraser => {
        paintable.value?.setThicknessEraser(thicknessEraser!);
      }
    );

    watch(
      () => props.thickness,
      thickness => {
        paintable.value?.setThickness(thickness!);
      }
    );

    watch(
      () => props.color,
      color => {
        paintable.value?.setColor(color!);
      }
    );

    watch(
      () => props.scaleFactor,
      scaleFactor => {
        paintable.value?.setScaleFactor(scaleFactor!);
      }
    );

    const undo = () => {
      paintable.value?.undo();
    };

    const redo = () => {
      paintable.value?.redo();
    };

    const clear = () => {
      paintable.value?.clearCanvas();
    };

    onMounted(() => {
      console.log(",sf", canvas.value);
      paintable.value = new PaintableCore(canvas.value as HTMLCanvasElement, {
        width: props.width,
        height: props.height,
        active: props.active,
        scaleFactor: props.scaleFactor,
        useEraser: props.useEraser,
        thicknessEraser: props.thicknessEraser,
        thickness: props.thickness,
        color: props.color,
        image: props.image,
        onLongPress: () => emit("longPress"),
        onSave: image => emit("save", image)
      });
      console.log(paintable.value);
    });

    return {
      canvas,
      undo,
      redo,
      clear
    };
  }
});
</script>

// packages/bindings/react/src/lib/Paintable.tsx
import React, {
  forwardRef,
  ReactNode,
  Ref,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
} from 'react';
import { Paintable as PaintableCore } from 'paintablejs';

interface Props {
  // required
  width: number;
  height: number;
  active: boolean;

  //optional
  scaleFactor?: number;
  useEraser?: boolean;
  thicknessEraser?: number;
  thickness?: number;
  color?: string;
  smooth?: boolean;
  image?: string;

  onSave: (image: string) => void;
  onLongPress: () => void;
  children?: ReactNode;
}

export interface PaintableRef {
  undo: () => void;
  redo: () => void;
  clear: () => void;
}

export const Paintable = forwardRef((props: Props, ref: Ref<PaintableRef>) => {
  const canvas = useRef<HTMLCanvasElement>(null);
  const [paintable, setPaintable] = useState<PaintableCore | null>(null);
  const {
    width,
    height,
    active,

    scaleFactor,
    useEraser,
    thicknessEraser,
    thickness,
    color,
    smooth,
    image,

    onLongPress,
    onSave,
  } = props;

  useImperativeHandle(ref, () => {
    return {
      undo() {
        undo();
      },
      redo() {
        redo();
      },
      clear() {
        clear();
      },
    };
  });

  useEffect(() => {
    if (canvas.current) {
      const instance = new PaintableCore(canvas.current, {
        width,
        height,
        active,

        scaleFactor,
        useEraser,
        thicknessEraser,
        thickness,
        color,
        smooth,
        image,
        onLongPress,
        onSave,
      });
      setPaintable(instance);
    }
  }, [canvas]);

  useEffect(() => {
    paintable?.setThickness(thickness);
  }, [thickness]);

  useEffect(() => {
    paintable?.setUseEraser(useEraser);
  }, [useEraser]);

  useEffect(() => {
    paintable?.setScaleFactor(scaleFactor);
  }, [scaleFactor]);

  useEffect(() => {
    paintable?.setSmooth(smooth);
  }, [smooth]);

  useEffect(() => {
    paintable?.setActive(active);
  }, [active]);

  useEffect(() => {
    paintable?.setColor(color);
  }, [color]);

  const undo = () => {
    paintable?.undo();
  };
  const redo = () => {
    paintable?.redo();
  };

  const clear = () => {
    paintable?.clearCanvas();
  };

  return (
    <>
      <canvas ref={canvas}></canvas>

      <div
        style={{
          width: `${width}px`,
          height: `${height}px`,
        }}
      >
        {props.children}
      </div>
    </>
  );
});
