// packages/libs/vue/src/lib/Paintable.vue
<template>
  <div
    id="vue-paintable-container"
    :style="{
      width: `${width}px`,
      height: `${height}px`,
    }"
  >
    <canvas ref="canvas" :width="width" :height="height"></canvas>

    <div id="vue-paintable-inner">
      <slot></slot>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import { Paintable as PaintableCore } from '@paintablejs/core';

interface Data {
  paintable: null | PaintableCore;
}

export default Vue.extend({
  props: {
    width: {
      type: Number,
      required: true,
    },
    height: {
      type: Number,
      required: true,
    },
    active: {
      type: Boolean,
      required: true,
    },
    scaleFactor: {
      type: Number,
      required: false,
    },
    useEraser: {
      type: Boolean,
      required: false,
    },
    thicknessEraser: {
      type: Number,
      required: false,
    },
    thickness: {
      type: Number,
      required: false,
    },
    color: {
      type: String,
      required: false,
    },
    image: {
      type: String,
      required: false,
    },
  },
  data(): Data {
    return {
      paintable: null,
    };
  },
  watch: {
    active: function(active: boolean) {
      this.paintable?.setActive(active);
    },
    useEraser: function(useEraser: boolean) {
      this.paintable?.setUseEraser(useEraser);
    },
    thicknessEraser: function(thicknessEraser: number) {
      this.paintable?.setThicknessEraser(thicknessEraser);
    },
    thickness: function(thickness: number) {
      this.paintable?.setThickness(thickness);
    },
    color: function(color: string) {
      this.paintable?.setColor(color);
    },
    scaleFactor: function(scaleFactor: number) {
      this.paintable?.setScaleFactor(scaleFactor);
    },
  },
  methods: {
    undo() {
      this.paintable?.undo();
    },

    redo() {
      this.paintable?.redo();
    },

    clear() {
      this.paintable?.clearCanvas();
    },
  },

  mounted() {
    this.paintable = new PaintableCore(this.$refs.canvas as HTMLCanvasElement, {
      width: this.width,
      height: this.height,
      active: this.active,

      scaleFactor: this.scaleFactor,
      useEraser: this.useEraser,
      thicknessEraser: this.thicknessEraser,
      thickness: this.thickness,
      color: this.color,
      image: this.image,
      onLongPress: () => this.$emit('longPress'),
      onSave: (image) => this.$emit('save', image),
    });
  },
});
</script>

<style lang="scss" scoped>
#vue-paintable-container {
  #vue-paintable-inner {
    width: 100%;
    height: 100%;
  }
}
</style>

// packages/react/src/lib/Paintable.tsx
import React, {
  forwardRef,
  ReactNode,
  Ref,
  useEffect,
  useImperativeHandle,
  useRef,
  useState,
} from 'react';
import { Paintable as PaintableCore } from 'paintablejs';

interface Props {
  // required
  width: number;
  height: number;
  active: boolean;

  //optional
  scaleFactor?: number;
  useEraser?: boolean;
  thicknessEraser?: number;
  thickness?: number;
  color?: string;
  smooth?: boolean;
  image?: string | null;

  onSave: (image: string) => void;
  onLongPress: () => void;
  children?: ReactNode;
}

export interface PaintableRef {
  undo: () => void;
  redo: () => void;
  clear: () => void;
}

export const Paintable = forwardRef((props: Props, ref: Ref<PaintableRef>) => {
  const canvas = useRef<HTMLCanvasElement>(null);
  const [paintable, setPaintable] = useState<PaintableCore | null>(null);
  const {
    width,
    height,
    active,

    scaleFactor,
    useEraser,
    thicknessEraser,
    thickness,
    color,
    smooth,
    image,

    onLongPress,
    onSave,
  } = props;

  useImperativeHandle(ref, () => {
    return {
      undo() {
        undo();
      },
      redo() {
        redo();
      },
      clear() {
        clear();
      },
    };
  });

  useEffect(() => {
    if (canvas.current) {
      const instance = new PaintableCore(canvas.current, {
        width,
        height,
        active,

        scaleFactor,
        useEraser,
        thicknessEraser,
        thickness,
        color,
        smooth,
        image,
      });
      setPaintable(instance);
    }
  }, [canvas]);

  useEffect(() => {
    paintable?.events.on('save', onSave);
    paintable?.events.on('longPress', onLongPress);
  }, [paintable]);

  useEffect(() => {
    paintable?.setThickness(thickness);
  }, [thickness]);

  useEffect(() => {
    paintable?.setUseEraser(useEraser);
  }, [useEraser]);

  useEffect(() => {
    paintable?.setScaleFactor(scaleFactor);
  }, [scaleFactor]);

  useEffect(() => {
    paintable?.setSmooth(smooth);
  }, [smooth]);

  useEffect(() => {
    paintable?.setActive(active);
  }, [active]);

  useEffect(() => {
    paintable?.setColor(color);
  }, [color]);

  const undo = () => {
    paintable?.undo();
  };
  const redo = () => {
    paintable?.redo();
  };

  const clear = () => {
    paintable?.clearCanvas();
  };

  return (
    <>
      <canvas ref={canvas}></canvas>

      <div
        style={{
          width: `${width}px`,
          height: `${height}px`,
        }}
      >
        {props.children}
      </div>
    </>
  );
});
