// packages/examples/vue/src/App.vue
<template>
  <div id="main">
    <div>
      <button @click="clear">Clear</button>
      <button @click="undo">Undo</button>
      <button @click="redo">Redo</button>
      <button @click="toggleEdit">
        {{ active ? "save" : "edit" }}
      </button>
      <button @click="toggleEraser">
        {{ useEraser ? "use pencil" : "use eraser" }}
      </button>
      <label>
        Smooth:
        <input type="checkbox" v-model="smooth" />
      </label>
      <input type="color" v-model="color" />
      <input
        type="range"
        v-model.number="thickness"
        :min="1"
        :max="30"
        :step="1"
      />
    </div>
    <Paintable
      ref="paintable"
      :width="1024"
      :height="768"
      :active="active"
      :color="color"
      :smooth="smooth"
      :thickness="thickness"
      :useEraser="useEraser"
      :image="image"
      @longPress="onLongPress"
      @save="onSave"
    >
      <div id="paintable-children">Test</div>
    </Paintable>
  </div>
</template>

<script lang="ts">
import { Component, Vue, Watch } from "vue-property-decorator";

import { Paintable } from "paintablejs/vue";

@Component({
  components: {
    Paintable,
  },
})
export default class App extends Vue {
  useEraser = false;
  color = "#FF0000";
  thickness = 5;
  active = false;
  smooth = false;

  paintable: null | Paintable = null;

  mounted() {
    this.paintable = this.$refs.paintable as Paintable;
  }

  clear() {
    this.paintable?.clear();
  }

  undo() {
    this.paintable?.undo();
  }

  redo() {
    this.paintable?.redo();
  }

  get image() {
    return localStorage.getItem("/");
  }

  onSave(image: string) {
    localStorage.setItem("/", image);
  }

  onLongPress() {
    console.log("longPress");
  }

  toggleEraser() {
    this.useEraser = !this.useEraser;
  }

  toggleEdit() {
    this.useEraser = false;
    this.active = !this.active;
  }
}
</script>

<style lang="scss" scoped>
#paintable-children {
  background-color: green;
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
}
</style>>

// packages/examples/angular/src/app/app.component.ts
import { Component, ViewChild } from '@angular/core';
import { PaintableComponent } from '@paintablejs/angular';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  @ViewChild(PaintableComponent)
  paintable: PaintableComponent;

  active = false;
  useEraser = false;
  thickness = 5;
  color = '#FF0000';

  clear() {
    this.paintable?.clear();
  }

  undo() {
    this.paintable?.undo();
  }

  redo() {
    this.paintable?.redo();
  }

  toggleEdit() {
    this.useEraser = false;
    this.active = !this.active;
  }

  toggleUseEraser() {
    this.useEraser = !this.useEraser;
  }

  get image() {
    return localStorage.getItem('/') || undefined;
  }

  onSave(image: string) {
    localStorage.setItem('/', image);
  }

  onLongPress() {
    console.log('longpress');
  }
}

<div>
  <button (click)="clear()">Clear</button>
  <button (click)="undo()">Undo</button>
  <button (click)="redo()">Redo</button>
  <button (click)="toggleEdit()">
    {{ active ? "save" : "edit" }}
  </button>
  <button (click)="toggleUseEraser()">
    {{ useEraser ? "use pencil" : "use eraser" }}
  </button>
  <label> Smooth: <input type="checkbox" [(ngModel)]="smooth" /> </label>
  <input type="color" [(ngModel)]="color" />
  <input type="range" [(ngModel)]="thickness" min="{1}" max="{30}" step="{1}" />

  <paintable
    #paintable
    [width]="1024"
    [height]="768"
    [active]="active"
    [useEraser]="useEraser"
    [thickness]="thickness"
    [smooth]="smooth"
    [color]="color"
    [image]="image"
    (onSave)="onSave($event)"
    (onLongPress)="onLongPress()"
  >
    <div class="canvas-inner">test</div>
  </paintable>
</div>
