// example/src/App.tsx
import React, { useRef, useState } from 'react';
import { Paintable, PaintableRef } from 'react-paintable';
import styles from './App.module.css';

function App() {
  const paintableRef = useRef<PaintableRef>(null);
  const [color, setColor] = useState('blue');
  const [active, setActive] = useState(false);
  const [thickness, setThickness] = useState(5);
  const [useEraser, setUseEraser] = useState(false);
  return (
    <div>
      <div>
        <button onClick={() => paintableRef.current?.undo()}>Undo</button>
        <button onClick={() => paintableRef.current?.redo()}>Redo</button>
        <button
          onClick={() => {
            setUseEraser(false);
            setActive(!active);
          }}
        >
          {active ? 'save' : 'edit'}
        </button>
        <button onClick={() => setUseEraser(!useEraser)}>
          {useEraser ? 'use pencil' : 'use eraser'}
        </button>
        <input type="color" onChange={(e) => setColor(e.target.value)} />
        <input
          type="range"
          defaultValue={5}
          onChange={(e) => setThickness(Number(e.target.value))}
          min={1}
          max={30}
          step={1}
        />
      </div>

      <Paintable
        width={1024}
        height={768}
        active={active}
        color={color}
        thickness={thickness}
        useEraser={useEraser}
        ref={paintableRef}
        image={localStorage.getItem('/')}
        onSave={(image: string) => localStorage.setItem('/', image)}
        onLongPress={() => console.log('long')}
      >
        <div className={styles['canvas-inner']}>Test</div>
      </Paintable>
    </div>
  );
}

export default App;

// packages/examples/angular/src/app/app.component.ts
import { Component, ViewChild } from '@angular/core';
import { PaintableComponent } from 'paintablejs/angular';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  @ViewChild(PaintableComponent)
  paintable: PaintableComponent;

  active = false;
  useEraser = false;
  thickness = 5;
  color = '#FF0000';

  clear() {
    this.paintable?.clear();
  }

  undo() {
    this.paintable?.undo();
  }

  redo() {
    this.paintable?.redo();
  }

  toggleEdit() {
    this.useEraser = false;
    this.active = !this.active;
  }

  toggleUseEraser() {
    this.useEraser = !this.useEraser;
  }

  get image() {
    return localStorage.getItem('/') || undefined;
  }

  onSave(image: string) {
    localStorage.setItem('/', image);
  }

  onLongPress() {
    console.log('longpress');
  }
}

<div>
  <button (click)="clear()">Clear</button>
  <button (click)="undo()">Undo</button>
  <button (click)="redo()">Redo</button>
  <button (click)="toggleEdit()">
    {{ active ? "save" : "edit" }}
  </button>
  <button (click)="toggleUseEraser()">
    {{ useEraser ? "use pencil" : "use eraser" }}
  </button>
  <input type="color" [(ngModel)]="color" />
  <input type="range" [(ngModel)]="thickness" min="{1}" max="{30}" step="{1}" />

  <paintable
    #paintable
    [width]="1024"
    [height]="768"
    [active]="active"
    [useEraser]="useEraser"
    [thickness]="thickness"
    [smooth]="smooth"
    [color]="color"
    [image]="image"
    (onSave)="onSave($event)"
    (onLongPress)="onLongPress()"
  >
    <div class="canvas-inner">test</div>
  </paintable>
</div>
